# Generated by Django 4.2.2 on 2023-09-21 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('track', '0001_initial'),
        ('rendition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendition',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendition_track', to='track.track'),
        ),
        migrations.AlterUniqueTogether(
            name='renditionvote',
            unique_together={('rendition', 'user')},
        ),
    ]
