# Generated by Django 4.2.2 on 2023-09-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendition', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendition',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
