# Generated by Django 4.2.2 on 2023-09-21 20:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(max_length=65535)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
