# Generated by Django 4.2.2 on 2023-09-21 20:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('displayname', models.CharField(max_length=255)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('lastOnline', models.DateTimeField(auto_now=True)),
                ('access', models.IntegerField(choices=[(0, 'Banned'), (10, 'Member'), (20, 'Trusted'), (30, 'Moderator'), (40, 'Administrator')], default=10)),
            ],
        ),
    ]
