# Generated by Django 4.2.2 on 2023-09-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='trackNumber',
            field=models.SmallIntegerField(null=True),
        ),
    ]
